version: '3.4'

services:
  contactlistdb:
   container_name: contactlistdb
   restart: always
   volumes:
    - ${WEBAPP_STORAGE_HOME}/site:/data/db
    #- ./data:/data/db
   ports:
    - "27017:27017"
  rabbitmq:
   container_name: rabbitmq
   restart: always
   ports:
     - "5672:5672"
     - "15672:15672"
  contactlist.contacts:
    container_name: contactlistcontacts
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ContactDatabaseSettings:ConnectionString=mongodb://contactlistdb:27017"
    depends_on:
        - contactlistdb
    ports:
      - "8000:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  contactlist.reporting:
    container_name: contactlistreporting
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ReportDatabaseSettings:ConnectionString=mongodb://contactlistdb:27017"
      - "EventBus:HostName=rabbitmq"
    depends_on:
      - contactlistdb
      - rabbitmq
    ports:
      - "8001:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  contactlist.apigateway:
   container_name: contactlistapigateway
   environment:
    - ASPNETCORE_ENVIRONMENT=Development
   depends_on:
    - contactlist.contacts
    - contactlist.reporting
   ports:
    - "5000:80"
   volumes:
    - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
    - ${HOME}/.aspnet/https:/root/.aspnet/https/

