version: '3.4'

services:
  contactlistdb:
   container_name: contactlistdb
   restart: always
   volumes:
    - ${WEBAPP_STORAGE_HOME}/site:/data/db
    #- ./data:/data/db
   ports:
    - "27017:27017"
  contactlist.contacts:
    container_name: contactlistcontacts
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ContactDatabaseSettings:ConnectionString=mongodb://contactlistdb:27017"
    depends_on:
        - contactlistdb
    ports:
      - "8000:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  contactlist.reporting:
    container_name: contactlistreporting
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ReportDatabaseSettings:ConnectionString=mongodb://contactlistdb:27017"
    depends_on:
      - contactlistdb
    ports:
      - "8001:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
